use_frameworks!

platform :ios, '8.0'

target 'Example' do
  pod 'GYDModuleDemoSubModuleB', :path => '../'
  pod 'GYDModuleDemoInterface', 
    :git => 'git@github.com:pkgogai/GYDModuleDemoInterface.git', 
    :branch => 'dev'
end
